version: 0.2

phases:
  install:
    runtime-versions:
      terraform: 0.12
    commands:
      - echo Installing dependencies...
      - apt-get update && apt-get install -y unzip
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/0.12.29/terraform_0.12.29_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
  pre_build:
    commands:
      - echo Initializing Terraform...
      - terraform init
  build:
    commands:
      - echo Validating Terraform configuration...
      - terraform validate
      - echo Applying Terraform configuration...
      - terraform apply -auto-approve
artifacts:
  files:
    - '**/*'