name: Deploy EC2 and Install Nginx

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve

    - name: Install Nginx
      run: |
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_SSH_PRIVATE_KEY }} ec2-user@${{ steps.terraform.outputs.instance_ip }} << EOF
        sudo apt update -y
        sudo apt install nginx1 -y
        sudo systemctl start nginx
        sudo systemctl enable nginx
        EOF